name: LocationApplication

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: dotnet publish
      run: dotnet publish ./LA.Web/LA.Web.csproj -c Release --no-restore --no-dependencies -f netcoreapp3.1 --output ./publish --self-contained false
    - name: List output files
      run: ls publish
    - name: Local directory
      run: ls
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      env:
        FTP_SERVER: ${{ secrets.FTP_ADDRESS }}${{ secrets.FTP_PATH }}
        FTP_USERNAME: ${{ secrets.FTP_LOGIN }}
        FTP_PASSWORD: ${{ secrets.FTP_PASS }}
        LOCAL_DIR: publish
        METHOD: sftp
        ARGS: --delete
