name: LocationApplication

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --configuration Release --no-restore
    - name: Publish project
      run: dotnet publish ./LA.Web/LA.Web.csproj -c Release --no-restore --no-dependencies -f netcoreapp3.1 --output ./dane --self-contained false
    - name: Send files to FTP repository
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_ADDRESS }}${{ secrets.FTP_PATH }}
        user: ${{ secrets.FTP_LOGIN }}
        password: ${{ secrets.FTP_PASS }}
        localDir: "dane"
